import HeaderNavigation from '@/components/header/headerNavigation'
import NavigationContainer from '@/components/navigation/navigationContainer'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function AuthenticatedLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<HeaderNavigation />
				{children}
				<NavigationContainer />
			</body>
		</html>
	)
}
